// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1hPrP_KzmFAmbTIso94cSROFkTSXI8Iw',
    appId: '1:123640771640:web:16a8d34781921d755022cd',
    messagingSenderId: '123640771640',
    projectId: 'batta-aebb8',
    authDomain: 'batta-aebb8.firebaseapp.com',
    storageBucket: 'batta-aebb8.appspot.com',
    measurementId: 'G-2VFBJKXLBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoFrElBHYLP7hbho65DEeGplDLKHzk09Q',
    appId: '1:123640771640:android:a2a4dec507f6bd165022cd',
    messagingSenderId: '123640771640',
    projectId: 'batta-aebb8',
    storageBucket: 'batta-aebb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpQ9upWy0yatM0Ax-NCl9fEGgeoxIMSPU',
    appId: '1:123640771640:ios:d7deb7b9b9dfee8a5022cd',
    messagingSenderId: '123640771640',
    projectId: 'batta-aebb8',
    storageBucket: 'batta-aebb8.appspot.com',
    iosClientId: '123640771640-4ht8kfl42udobnan10iakoku069hnevt.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpQ9upWy0yatM0Ax-NCl9fEGgeoxIMSPU',
    appId: '1:123640771640:ios:d7deb7b9b9dfee8a5022cd',
    messagingSenderId: '123640771640',
    projectId: 'batta-aebb8',
    storageBucket: 'batta-aebb8.appspot.com',
    iosClientId: '123640771640-4ht8kfl42udobnan10iakoku069hnevt.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
